apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-alibi-explainer-28
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-alibi-explainer/kserve-alibi-explainer-28@sha256:e7a86a09e9b5de9492871aff37a79cabe5c37bb719836546b59492676d996a38
        name: container-image
        resources: {}
status: {}
